function escapeXml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function buildTableRow(values, { header = false, total = false } = {}) {
  const tag = header ? "th" : "td";
  const style = total
    ? ' style="font-weight:700;background:#f1f5f9;"'
    : header
    ? ' style="font-weight:700;background:#0f172a;color:#ffffff;"'
    : "";

  return `<tr${style}>${values
    .map((value) => `<${tag}>${escapeXml(value)}</${tag}>`)
    .join("")}</tr>`;
}

export function exportReportToExcel({
  fileName = "Report",
  sheetName = "Report",
  title = "Report",
  companyName = "Fleet Fuel PRO",
  generatedBy = "Current User",
  generatedAt = new Date().toLocaleString("en-GB"),
  filters = [],
  rows = [],
  totals = {},
}) {
  if (typeof document === "undefined") return;

  const headers = rows.length
    ? Object.keys(rows[0])
    : Object.keys(totals);

  const safeSheetName = String(sheetName || "Report")
    .replace(/[\\/?*[\]:]/g, " ")
    .slice(0, 31);

  const metadataRows = [
    [companyName],
    [title],
    [`Generated: ${generatedAt}`],
    [`Generated By: ${generatedBy}`],
    [],
    ...filters.map((item) => [item.label, item.value]),
    [],
  ];

  const dataRows = rows.map((row) =>
    headers.map((header) => row[header] ?? "")
  );

  const totalRow = headers.map((header) => totals[header] ?? "");

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="ProgId" content="Excel.Sheet" />
        <meta name="Generator" content="Fleet Fuel PRO" />
        <style>
          body { font-family: Arial, sans-serif; }
          table { border-collapse: collapse; }
          th, td { border: 1px solid #94a3b8; padding: 6px; }
          th { background: #0f172a; color: #ffffff; }
        </style>
      </head>
      <body>
        <table data-sheet-name="${escapeXml(safeSheetName)}">
          ${metadataRows.map((row) => buildTableRow(row)).join("")}
          ${buildTableRow(headers, { header: true })}
          ${dataRows.map((row) => buildTableRow(row)).join("")}
          ${buildTableRow(totalRow, { total: true })}
        </table>
      </body>
    </html>
  `;

  const blob = new Blob(["\ufeff", html], {
    type: "application/vnd.ms-excel;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const dateStamp = new Date().toISOString().slice(0, 10);

  link.href = url;
  link.download = `${fileName}_${dateStamp}.xls`;
  document.body.appendChild(link);
  link.click();
  link.remove();

  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
